module Amaterasu
  class Emulator
    CYCLES_PER_FRAME: Integer

    def initialize: (
      audio: String,
      cycles: Integer,
      debug: bool,
      profiling: String,
      steps: Integer,
      trace: String,
      video: String,
      rom_path: String
    ) -> void
    def start: (CLI::emulator_options options) -> void
    def advance_cycle: () -> void
    def stop: () -> void
  end
end
