# frozen_string_literal: true

module Akane
  module GameBoy
    class Cpu
      module Instructions
        class CbRl < Base
          include Utils::BitOps

          def initialize: (cpu: Cpu, target: Symbol) -> void

          private

          def build_logic: (Symbol target) -> Proc
          def rl_reg8: (Integer reg8_value) -> void
          def rl_mem_hl: () -> void
        end
      end
    end
  end
end
