# frozen_string_literal: true

module Amaterasu
  module GameBoy
    class Cpu
      module Instructions
        class Halt < Base
          def initialize: (cpu: Cpu) -> void
        end
      end
    end
  end
end
