# frozen_string_literal: true

module Amaterasu
  module GameBoy
    class Cpu
      module Instructions
        class Inc < Base
          def initialize: (cpu: Cpu, operand: Symbol) -> void

          private

          def build_logic: (Symbol operand) -> Proc
          def inc: (Integer value) -> Integer
          def inc16: (Integer value) -> void
        end
      end
    end
  end
end
