# frozen_string_literal: true

module Akane
  module GameBoy
    class Cpu
      module Instructions
        class Stop < Base
          def initialize: (cpu: Cpu) -> void
        end
      end
    end
  end
end
