plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/ComparableBetween:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10
