plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'lib/akane/gameboy/bus.rb'

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 20

Naming/AccessorMethodName:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/ComparableBetween:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/NumericPredicate:
  Enabled: false
