# frozen_string_literal: true

module Akane
  module Gameboy
    class Cpu
      module Instructions
        class Add16 < Base
          def initialize: (cpu: Cpu, target: Symbol, source: Symbol) -> void

          private

          def build_logic: (Symbol source, Symbol target) -> Proc
          def add16: (Integer value) -> void
          def add16_sig8: () -> void
        end
      end
    end
  end
end
