# frozen_string_literal: true

module Akane
  module Gameboy
    class Cpu
      module Instructions
        class CbRlc < Base
          def initialize: (cpu: Cpu, target: Symbol) -> void

          private

          def build_logic: (Symbol target) -> Proc
          def rlc_reg8: (Symbol reg8) -> void
          def rlc_mem_hl: () -> void
        end
      end
    end
  end
end
