# frozen_string_literal: true

module Akane
  module Gameboy
    class Cpu
      module Instructions
        class CbSra < Base
          include Utils::BitOps

          def initialize: (cpu: Cpu, target: Symbol) -> void

          private

          def build_logic: (Symbol target) -> Proc
          def sra_reg8: (Integer reg8) -> void
          def sra_mem_hl: () -> void
        end
      end
    end
  end
end
