# frozen_string_literal: true

module Akane
  module Gameboy
    class Cpu
      module Instructions
        class Di < Base
          def initialize: (cpu: Cpu) -> void
        end
      end
    end
  end
end
