# frozen_string_literal: true

module Amaterasu
  module GameBoy
    class Cpu
      module Instructions
        def self.load_base_instructions: (cpu: Cpu) -> void
        def self.load_cb_instructions: (cpu: Cpu) -> void
      end
    end
  end
end
