module Amaterasu
  class CLI
    type emulator_options = {
      audio: String?,
      cycles: Integer?,
      debug: bool,
      profile: Symbol?,
      steps: Integer?,
      trace: Array[String]?,
      renderer: String?,
      rom_path: String
    }

    def self.parse: (Array[String] arguments) -> emulator_options
  end
end
