module Akane
  module GameBoy
    class Interrupts
      type interrupt_types = :v_blank | :lcd_stat | :timer | :serial | :joypad

      TYPES: Hash[interrupt_types, Integer]
      VECTORS: Hash[interrupt_types, Integer]

      def initialize: (?skip_boot_rom: bool) -> void

      def if_register: () -> Integer
      def ie_register: () -> Integer
      def if_register=: (Integer value) -> void
      def ie_register=: (Integer value) -> void

      def any_pending?: () -> bool
      def highest_pending: () -> interrupt_types
      def request: (interrupt_types value) -> void
      def service: (interrupt_types value) -> void
      def priority_vector: () -> Integer
      def priority_service: () -> void

      private

      def pending?: (interrupt_types value) -> bool
    end
  end
end
