module Akane
  module GameBoy
    class Ram
      def initialize: (size: Integer, offset: Integer) -> void

      def read_byte: (address: Integer) -> Integer
      def write_byte: (address: Integer, value: Integer) -> void
      def read_backup: (address: Integer) -> Integer
      def disk_size: () -> String
      def save_data: () -> void
      def restore_data: () -> void
      def wipe_data: () -> void
      def wipe_backup: () -> void
    end
  end
end
