# frozen_string_literal: true

module Amaterasu
  module GameBoy
    class Cpu
      module Instructions
        class Base
          attr_reader mnemonic: String

          def initialize: (cpu: Cpu) -> void
          def execute: () -> void

          private

          def format_operand: (Symbol ?operand) -> String
        end
      end
    end
  end
end
