# frozen_string_literal: true

module Amaterasu
  module GameBoy
    class Cpu
      module Instructions
        class Jp < Base
          def initialize: (cpu: Cpu, location: Symbol, ?condition: Symbol) -> void

          private

          def build_logic: (Symbol location, Symbol ?condition) -> Proc
          def jp: (condition: bool) -> void
        end
      end
    end
  end
end
