module Akane
  module Gameboy
    class Cpu
      INSTRUCTIONS: Hash[Integer, Proc]
      CB_INSTRUCTIONS: Hash[Integer, Proc]

      attr_reader registers: Registers

      def initialize: (Bus bus, Hram hram, Interrupts interrupts, Proc advance_cycle, bool ?trace_cpu) -> void

      def step: () -> void

      def bus_read: (address: Integer) -> Integer
      def bus_write: (address: Integer, value: Integer) -> void
      def fetch_next_byte: () -> Integer
      def fetch_next_word: () -> Integer

      def sign_value: (Integer byte) -> Integer
      def add16: (Integer value1, Integer value2) -> Integer
      def sub16: (Integer value1, Integer value2) -> Integer

      def stack_push: (value: Integer) -> void
      def stack_pop: () -> Integer

      def jump_to: (address: Integer) -> void
      def halt: () -> void
      def enable_interrupts: () -> void
      def disable_interrupts: () -> void

      private

      def handle_interrupts: () -> void
      def decode_instruction: () -> void
      def execute_instruction: () -> void
      def internal_processing: () -> void
      def log_state: (Integer old_pc, Integer old_cycles, Instructions::Base instruction) -> void
    end
  end
end
