# frozen_string_literal: true

module Amaterasu
  module GameBoy
    class Ppu
      module Modes
        class VBlank
          attr_reader name: String
          attr_reader number: Integer

          def initialize: () -> void
          def tick: () -> void

          def to_s: () -> String
          def inspect: () -> String
        end
      end
    end
  end
end
