module Amaterasu
  module GameBoy
    class Bus
      def initialize: (
        cartridge: Amaterasu::Cartridge,
        ppu: Ppu,
        apu: Apu,
        wram: Ram,
        hram: Ram,
        interrupts: Interrupts,
        timer: Timer,
        serial: Serial,
        joypad: Joypad
      ) -> void

      def read_byte: (address: Integer) -> Integer
      def write_byte: (address: Integer, value: Integer) -> void

      private

      def read_io: (Integer address) -> Integer
      def write_io: (Integer address, Integer value) -> void
    end
  end
end
